services:
  - type: web
    name: question-paper-generator
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app --bind 0.0.0.0:$PORT
    autoDeploy: true